### ISSUE TITLE
make Ensembl genes the default

### ISSUE THREAD

**Issue by diekhans** [human-pangenomics/HPRC_Assembly_Hub#18]
pack Ensembl, hide CAT by default

**Comment by diekhans** [comment]
also make Ensembl default to show gene name

**Comment by Jeltje** [comment]
Did the first, tried changing `defaultLabelFields geneName` in trackDb.txt but that doesn't solve the issue - it still shows ENSG IDs.

**Comment by diekhans** [comment]
Since name2 column also has the gene symbol, lets try that.

I also fixed some of the descriptions in the .as file.  Means the bigBed need to be rebuilt.

**Comment by Jeltje** [comment]
Rebuilt! It works now.
