### ISSUE TITLE
Hub contact is incorrect

### ISSUE THREAD

**Issue by diekhans** [human-pangenomics/HPRC_Assembly_Hub#9]
They hub.txt file has mhauknes@ucsc.edu as the contact, and the GB support group is referring people to Marina, who no longer works on the project

Suggest making the github issues URL the contact

**Comment by juklucas** [comment]
Addressed in commit [2ece118](https://github.com/human-pangenomics/HPRC_Assembly_Hub/commit/2ece118ea24bea7128df55c0b8b5edd6a525c07a). The changes will be visible on the browser when we rebuild. Probably by Monday.
